spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootlibrary;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    

server:
  port: 8090

security:
  basic:
    enabled: false
    
#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false

project:
  name: contractApplication
  version: 0.1
  description: boot-library default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop

contract.service:
  name: 'test profile:'
  
logging:
  file: boot_library.log
  org.hibernate: INFO

 
